" JAVASCRIPT DOCS
nnoremap <buffer> <LEADER>dd :JsDoc<CR>

" SET INDENTATION PREFERENCES
set tabstop=2       " SHOW EXISTING WITH 2 SPACES WIDTH
set shiftwidth=2    " WHEN INDENTING WITH '>', USE 2 SPACES WIDTH
set expandtab       " ON PRESSING TAB, INSERT 2 SPACES
set softtabstop=2   " WHEN PRESSING BACKSPACE, SKIP 2 SPACES
set shiftround      " USE MULTIPLE OF SHIFT WIDTH WITH '>' & '<'
